package de.metis.modules.evolution;

import java.io.*;
import java.nio.file.*;
import java.time.Instant;
import java.util.logging.Logger;

/**
 * Phase 12b — FeatureBranchManager: erstellt Git-Branches + PRs.
 *
 * <p>Bei Aenderungen an Kernel/Core/Safety wird kein direkter Fix deployt,
 * sondern ein Feature-Branch erstellt und als GitHub PR vorgeschlagen.
 * Der menschliche Admin muss den PR freigeben, bevor der Build laeuft.
 */
public class FeatureBranchManager {

    private static final Logger LOG = Logger.getLogger(FeatureBranchManager.class.getName());

    private final Path repoDir;
    private final Path targetDir;
    private int branchCount = 0;

    public FeatureBranchManager(Path repoDir, Path targetDir) {
        this.repoDir = repoDir;
        this.targetDir = targetDir;
    }

    /**
     * Erstellt einen Feature-Branch + commit + PR-Hinweis.
     *
     * @return Branch-Name oder null bei Fehler
     */
    public String createBranch(String sourceFile, String fixCode, String description) {
        try {
            String safeName = description.replaceAll("[^a-zA-Z0-9]", "_");
            if (safeName.length() > 40) safeName = safeName.substring(0, 40);
            String branchName = "feature/" + safeName + "_" + Instant.now().getEpochSecond();

            // Git: stash working changes, create branch
            exec("git stash", repoDir);
            exec("git checkout master", repoDir);
            exec("git pull origin master 2>/dev/null || true", repoDir);
            exec("git checkout -b " + branchName, repoDir);

            // Apply the fix
            Path fullSource = targetDir.resolve(sourceFile);
            if (Files.exists(fullSource)) {
                Files.writeString(fullSource, fixCode);
                LOG.info("FeatureBranchManager: wrote fix to " + fullSource);
            } else {
                // Write as new file
                Files.createDirectories(fullSource.getParent());
                Files.writeString(fullSource, fixCode);
                LOG.info("FeatureBranchManager: created " + fullSource);
            }

            // Commit + push
            String commitMsg = "feature: " + description + " [auto-generated by Metis AGI]";
            exec("git add -A", repoDir);
            exec("git commit -m '" + commitMsg.replace("'", "") + "'", repoDir);
            exec("git push origin " + branchName + " 2>&1", repoDir);

            // Create PR via GitHub CLI if available
            String prBody = "## 🤖 Auto-generated Feature Branch\n\n"
                    + "This branch was created by **Metis AGI** (self-evolving agent).\n\n"
                    + "**Description:** " + description + "\n\n"
                    + "**Target file:** `" + sourceFile + "`\n\n"
                    + "**Action required:** Review and approve this PR to deploy.\n"
                    + "Internal sandbox tests passed, but full build requires approval.\n"
                    + "_Generated at " + Instant.now() + "_";
            try {
                String prCmd = "gh pr create --base master --head " + branchName
                        + " --title '" + commitMsg + "' --body '" + prBody.replace("'", "") + "'";
                exec(prCmd, repoDir);
            } catch (Exception e) {
                LOG.info("FeatureBranchManager: gh not available, PR must be created manually");
                // Write PR info to file
                Path prInfo = repoDir.resolve(".feature-prs").resolve(branchName + ".md");
                Files.createDirectories(prInfo.getParent());
                Files.writeString(prInfo, "Branch: " + branchName + "\nDesc: " + description + "\nFile: " + sourceFile);
            }

            // Restore working state
            exec("git checkout master", repoDir);
            exec("git stash pop 2>/dev/null || true", repoDir);

            branchCount++;
            LOG.info("FeatureBranchManager: created branch " + branchName);
            return branchName;

        } catch (Exception e) {
            LOG.warning("FeatureBranchManager: failed to create branch: " + e.getMessage());
            try {
                exec("git checkout master", repoDir);
                exec("git stash pop 2>/dev/null || true", repoDir);
            } catch (Exception ignored) {}
            return null;
        }
    }

    private String exec(String cmd, Path dir) throws Exception {
        ProcessBuilder pb = new ProcessBuilder("bash", "-c", cmd);
        pb.directory(dir.toFile());
        pb.redirectErrorStream(true);
        Process p = pb.start();
        String out = new String(p.getInputStream().readAllBytes());
        int code = p.waitFor();
        if (code != 0) LOG.fine("FeatureBranchManager: cmd '" + cmd.substring(0, Math.min(60, cmd.length()))
                + "' exited " + code + ": " + out.substring(0, Math.min(100, out.length())));
        return out;
    }

    public int branchCount() { return branchCount; }
}
