package de.metis.kernel.action;

import de.metis.kernel.mcp.McpClientService;

import java.time.Instant;
import java.util.Map;
import java.util.logging.Logger;

/**
 * Invokes a single MCP tool on a connected server.
 * <p>
 * Generated by {@link McpBridgeAction} after tool discovery.
 * Each discovered MCP tool gets one instance of this action.
 * <p>
 * Category: depends on tool. Approval: NOTIFY (tools can modify state).
 */
public class McpToolInvocationAction implements Action {

    private static final Logger LOG = Logger.getLogger(McpToolInvocationAction.class.getName());

    private final McpClientService client;
    private final String toolName;
    private final String toolDescription;
    private final Map<String, Object> arguments;

    public McpToolInvocationAction(McpClientService client, String toolName,
                                   String toolDescription, Map<String, Object> arguments) {
        this.client = client;
        this.toolName = toolName;
        this.toolDescription = toolDescription;
        this.arguments = arguments;
    }

    @Override public String name() { return "mcp:" + toolName; }
    @Override public String category() { return "mcp-tool"; }
    @Override public ApprovalLevel approvalLevel() { return ApprovalLevel.NOTIFY; }

    @Override
    public ActionResult execute() {
        var now = Instant.now();
        try {
            if (!client.isConnected()) {
                return ActionResult.fail(name(), "MCP server disconnected", now);
            }
            String result = client.callTool(toolName, arguments);
            LOG.fine(() -> "MCP tool " + toolName + " OK (" + result.length() + " chars)");
            return ActionResult.ok(name(), result, now);
        } catch (Exception e) {
            LOG.warning("MCP tool " + toolName + " failed: " + e.getMessage());
            return ActionResult.fail(name(), "MCP tool error: " + e.getMessage(), now);
        }
    }

    public String toolDescription() { return toolDescription; }
}
